# Generated by Django 6.0.4 on 2026-05-04 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم المساحة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('space_type', models.CharField(choices=[('office', 'مكتب'), ('hall', 'قاعة'), ('studio', 'استوديو'), ('warehouse', 'مستودع'), ('event', 'مساحة فعاليات'), ('meeting', 'قاعة اجتماعات'), ('coworking', 'مساحة عمل مشتركة'), ('training', 'غرفة تدريب')], default='office', max_length=20, verbose_name='نوع المساحة')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('unavailable', 'غير متاح')], default='available', max_length=20, verbose_name='الحالة')),
                ('city', models.CharField(choices=[('riyadh', 'الرياض'), ('jeddah', 'جدة'), ('makkah', 'مكة المكرمة'), ('dammam', 'الدمام'), ('madinah', 'المدينة المنورة')], default='riyadh', max_length=20, verbose_name='المدينة')),
                ('address', models.CharField(max_length=300, verbose_name='العنوان')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر / يوم (ريال)')),
                ('price_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر / شهر (ريال)')),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر / سنة (ريال)')),
                ('rental_type', models.CharField(choices=[('daily', 'يومي'), ('monthly', 'شهري'), ('yearly', 'سنوي')], default='daily', max_length=10, verbose_name='نوع الإيجار')),
                ('capacity', models.IntegerField(default=1, verbose_name='السعة (أشخاص)')),
                ('area_sqm', models.FloatField(default=0, verbose_name='المساحة (م²)')),
                ('maps_embed_url', models.URLField(blank=True, verbose_name='رابط تضمين خرائط Google')),
                ('video_url', models.URLField(blank=True, verbose_name='رابط فيديو (YouTube/Vimeo)')),
                ('virtual_tour', models.URLField(blank=True, verbose_name='جولة افتراضية 360°')),
                ('allow_dynamic_pricing', models.BooleanField(default=False, verbose_name='تسعير ديناميكي')),
                ('discount_pct', models.PositiveSmallIntegerField(default=0, verbose_name='نسبة الخصم %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'مساحة',
                'verbose_name_plural': 'المساحات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='spaces/', verbose_name='صورة')),
                ('is_main', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spaces.space')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('catering', 'ضيافة وتقديم طعام'), ('photography', 'تصوير فوتوغرافي'), ('decoration', 'ديكور وتنسيق'), ('organizers', 'منظمو فعاليات'), ('sound', 'نظام صوت'), ('chairs', 'كراسي وطاولات إضافية'), ('security_svc', 'خدمة أمن'), ('cleaning', 'تنظيف ما بعد الفعالية')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر (ريال)')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='وصف مختصر')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='spaces.space')),
            ],
            options={
                'verbose_name': 'خدمة إضافية',
                'verbose_name_plural': 'الخدمات الإضافية',
                'unique_together': {('space', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='SpaceAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('screen', 'شاشة عرض'), ('coffee', 'كورنر قهوة'), ('parking', 'مواقف سيارات'), ('wifi', 'إنترنت عالي السرعة'), ('ac', 'تكييف مركزي'), ('whiteboard', 'لوح أبيض'), ('projector', 'بروجكتر'), ('kitchen', 'مطبخ صغير'), ('printer', 'طابعة'), ('reception', 'استقبال'), ('security', 'حراسة أمنية'), ('elevator', 'مصعد')], max_length=30, verbose_name='الميزة')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='spaces.space')),
            ],
            options={
                'verbose_name': 'ميزة',
                'verbose_name_plural': 'المميزات',
                'unique_together': {('space', 'name')},
            },
        ),
    ]
