# Generated by Django 6.0.4 on 2026-05-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='space',
            name='virtual_tour',
        ),
        migrations.AlterField(
            model_name='space',
            name='allow_dynamic_pricing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='space',
            name='discount_pct',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='نسبة الخصم %'),
        ),
    ]
